--USE master;
--go
--DROP DATABASE MONITORIA_FATEC;
--GO
CREATE DATABASE MONITORIA_FATEC;
GO 
USE MONITORIA_FATEC;
GO
Create Table SCOPE(
	IDSCOPE INT IDENTITY(1,1) NOT NULL,
	SCOPE VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_SCOPE] PRIMARY KEY CLUSTERED 
(
	IDSCOPE ASC
));

GO

Create Table USUARIO(
	IDUSER INT IDENTITY(1,1) NOT NULL,
	USERPASSWORD VARCHAR(255) NOT NULL,
	NMUSER VARCHAR(255) NOT NULL,
	EMAILUSER VARCHAR(255) NOT NULL,
	IDSCOPE INT NOT NULL,
	 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	IDUSER ASC
));

GO

ALTER TABLE [dbo].USUARIO  WITH CHECK ADD  CONSTRAINT [FK_SCOPE] FOREIGN KEY(IDSCOPE)
REFERENCES [dbo].SCOPE (IDSCOPE)
GO

ALTER TABLE [dbo].USUARIO CHECK CONSTRAINT [FK_SCOPE]
GO

Create Table DISCIPLINE(
	IDDISCIPLINE INT IDENTITY(1,1) NOT NULL,
	NMDISCIPLINE VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_DISCIPLINE] PRIMARY KEY CLUSTERED 
(
	IDDISCIPLINE ASC
)
	);
	
GO 

Create Table COURSE(
	IDCOURSE INT IDENTITY(1,1) NOT NULL,
	IDCOORDINATOR INT,
	NMCOURSE VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_COURSE] PRIMARY KEY CLUSTERED 
(
	IDCOURSE ASC
));

GO

Create Table SCHEDULE(
	IDTEACHER INT,
	IDDISCIPLINE INT NOT NULL,
	IDCOURSE INT NOT NULL,
	SEMESTER VARCHAR(255) NOT NULL,
	PERIOD CHAR NOT NULL,
	IDMONITOR INT);

GO
ALTER TABLE [dbo].SCHEDULE  WITH CHECK ADD  CONSTRAINT [FK_DISCIPLINE] FOREIGN KEY(IDDISCIPLINE)
REFERENCES [dbo].DISCIPLINE (IDDISCIPLINE)
GO

ALTER TABLE [dbo].SCHEDULE CHECK CONSTRAINT [FK_DISCIPLINE]
GO
ALTER TABLE [dbo].SCHEDULE  WITH CHECK ADD  CONSTRAINT [FK_COURSE] FOREIGN KEY(IDCOURSE)
REFERENCES [dbo].COURSE (IDCOURSE)
GO

ALTER TABLE [dbo].SCHEDULE CHECK CONSTRAINT [FK_DISCIPLINE]
GO

 
Create Table STATUSCONTENT(
	IDSTATUS INT IDENTITY(1,1) NOT NULL,
	NMSTATUS VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_STATUSCONTENT] PRIMARY KEY CLUSTERED 
(
	IDSTATUS ASC
));


GO
 
Create Table TYPECONTENT(
	IDTYPECONTENT INT IDENTITY(1,1) NOT NULL,
	NMTYPECONTENT VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_TYPECONTENT] PRIMARY KEY CLUSTERED 
(
	IDTYPECONTENT ASC
));


GO 

Create Table CONTENT(
	IDCONTENT INT IDENTITY(1,1) NOT NULL,
	IDAUTHOR INT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	IDTYPECONTENT INT NOT NULL,
	CONTENT VARCHAR(255) NOT NULL,
	INFOCONTENT VARCHAR(255) NOT NULL,
	DATECONTENT DATETIME NOT NULL,
	IDSTATUS INT NOT NULL,
	 CONSTRAINT [PK_CONTENT] PRIMARY KEY CLUSTERED 
(
	IDCONTENT ASC
));

GO 
ALTER TABLE [dbo].CONTENT  WITH CHECK ADD  CONSTRAINT [FK_TYPECONTENT] FOREIGN KEY(IDTYPECONTENT)
REFERENCES [dbo].TYPECONTENT (IDTYPECONTENT)
GO

ALTER TABLE [dbo].CONTENT CHECK CONSTRAINT [FK_TYPECONTENT]
GO

ALTER TABLE [dbo].CONTENT  WITH CHECK ADD  CONSTRAINT [FK_STATUSCONTENT] FOREIGN KEY(IDSTATUS)
REFERENCES [dbo].STATUSCONTENT (IDSTATUS)
GO

ALTER TABLE [dbo].CONTENT CHECK CONSTRAINT [FK_STATUSCONTENT]
GO



Create Table TYPEMESSAGE(
	IDTYPEMESSAGE INT IDENTITY(1,1) NOT NULL,
	NMTYPEMESSAGE VARCHAR(255) NOT NULL,
	 CONSTRAINT [PK_TYPEMESSAGE] PRIMARY KEY CLUSTERED 
(
	IDTYPEMESSAGE ASC
));

GO 

Create Table USERMESSAGE(
	IDMESSAGE INT IDENTITY(1,1) NOT NULL,
	IDAUTHOR INT NOT NULL,
	IDRECIVER INT NOT NULL,
	HEADER VARCHAR(255) NOT NULL,
	BODY VARCHAR(MAX) NOT NULL,
	MESSAGEDATE DATETIME NOT NULL,
	IDORIGINMESSAGE INT,
	IDTYPEMESSAGE INT NOT NULL,
	 CONSTRAINT [PK_USERMESSAGE] PRIMARY KEY CLUSTERED 
(
	IDMESSAGE ASC
));

GO

ALTER TABLE [dbo].USERMESSAGE  WITH CHECK ADD  CONSTRAINT [FK_TYPEMESSAGE] FOREIGN KEY(IDTYPEMESSAGE)
REFERENCES [dbo].TYPEMESSAGE (IDTYPEMESSAGE)
GO

ALTER TABLE [dbo].USERMESSAGE CHECK CONSTRAINT [FK_TYPEMESSAGE]

go


Create Table CALENDAR(
	IDCALENDARIO INT IDENTITY(1,1) NOT NULL,
	DATE_HOUR DATETIME NOT NULL,
	IDMONITOR INT NOT NULL,
	EVENTO VARCHAR(255) NULL,
	ID_DISCIPLINE INT NOT NULL,
	 CONSTRAINT [PK_CALENDAR] PRIMARY KEY CLUSTERED 
(
	IDCALENDARIO ASC
));

GO

ALTER TABLE [dbo].CALENDAR  WITH CHECK ADD  CONSTRAINT [FK_USER_MONITOR] FOREIGN KEY(IDMONITOR)
REFERENCES [dbo].USUARIO (IDUSER)
GO

ALTER TABLE [dbo].CALENDAR CHECK CONSTRAINT [FK_USER_MONITOR]
GO

ALTER TABLE [dbo].CALENDAR  WITH CHECK ADD  CONSTRAINT [FK_DISCIPLINE_CALENDAR] FOREIGN KEY(ID_DISCIPLINE)
REFERENCES [dbo].DISCIPLINE (IDDISCIPLINE)
GO

ALTER TABLE [dbo].CALENDAR CHECK CONSTRAINT [FK_DISCIPLINE_CALENDAR]
GO