use MONITORIA_FATEC
--go 
--DROP TABLE CONTENT;
GO 
Create Table CONTENT(
	IDCONTENT INT IDENTITY(0,1) NOT NULL,
	IDAUTHOR INT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	IDTYPECONTENT VARCHAR(255) NOT NULL,
	CONTENT VARCHAR(255) NOT NULL,
	INFOCONTENT VARCHAR(255) NOT NULL,
	DATECONTENT DATETIME NOT NULL,
	IDSTATUS INT NOT NULL);