use MONITORIA_FATEC
--go 
--DROP TABLE SCHEDULE;
GO 
Create Table SCHEDULE(
	IDTEACHER INT,
	IDDISCIPLINE INT NOT NULL,
	IDCOURSE INT NOT NULL,
	SEMESTER VARCHAR(255) NOT NULL,
	PERIOD CHAR NOT NULL,
	IDMONITOR INT);