use MONITORIA_FATEC
--go 
--DROP TABLE USERMESSAGE;
GO 
Create Table USERMESSAGE(
	IDMESSAGE INT IDENTITY(0,1) NOT NULL,
	IDAUTHOR INT NOT NULL,
	IDRECIVER VARCHAR(255) NOT NULL,
	HEADER VARCHAR(255) NOT NULL,
	BODY VARCHAR(MAX) NOT NULL,
	MESSAGEDATE DATETIME NOT NULL,
	IDORIGINMESSAGE INT,
	IDTYPEMESSAGE INT NOT NULL);