use MONITORIA_FATEC
--go 
--DROP TABLE USUARIO;
GO 
Create Table USUARIO(
	IDUSER INT IDENTITY(0,1) NOT NULL,
	USERPASSWORD VARCHAR(255) NOT NULL,
	NMUSER VARCHAR(255) NOT NULL,
	IDSCOPE INT NOT NULL);