//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoriaFatec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR
    {
        public int IDCALENDARIO { get; set; }
        public System.DateTime DATE_HOUR { get; set; }
        public int IDMONITOR { get; set; }
        public string EVENTO { get; set; }
        public int ID_DISCIPLINE { get; set; }
    
        public virtual DISCIPLINE DISCIPLINE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
