//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoriaFatec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        public int IDCONTENT { get; set; }
        public int IDAUTHOR { get; set; }
        public string TITLE { get; set; }
        public int IDTYPECONTENT { get; set; }
        public string CONTENT1 { get; set; }
        public string INFOCONTENT { get; set; }
        public System.DateTime DATECONTENT { get; set; }
        public int IDSTATUS { get; set; }
    
        public virtual STATUSCONTENT STATUSCONTENT { get; set; }
        public virtual TYPECONTENT TYPECONTENT { get; set; }
    }
}
