//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoriaFatec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public Nullable<int> IDTEACHER { get; set; }
        public int IDDISCIPLINE { get; set; }
        public int IDCOURSE { get; set; }
        public string SEMESTER { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> IDMONITOR { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual DISCIPLINE DISCIPLINE { get; set; }
    }
}
